// src/pages/swollenballsallegations.tsx
import Script from 'next/script';
import * as React from 'react';

import { LayoutWhite as Layout } from '@/components/layout/Layout';
import ArrowLink from '@/components/links/ArrowLink';
import Seo from '@/components/Seo';

export default function ChromeGame() {
  return (
    <Layout>
      <Seo templateTitle='Life... is Roblox' />
      <Script src='scripts/chrome_game.js' />
      <div className='h-[33vh] px-4' id='game'></div>

      <div className='layout-l mt-5 text-left'>
        <h1
          style={{
            fontFamily: 'Open Sans',
            fontStyle: 'normal',
          }}
          className='text-xl text-red-600 md:text-4xl'
        >
          ⚠️ THIS PAGE HAS BEEN SEIZED
        </h1>
        <h2
          style={{
            fontFamily: 'Open Sans',
            fontStyle: 'normal',
            color: '#535353',
          }}
          className='mt-4 text-base md:text-2xl'
        >
          <span className='text-black'>Pokelawls, Inc.™</span> has ordered an
          immediate shutdown of this page, by court order.
        </h2>
      </div>
      <div className='layout-l mt-5 text-right'>
        <ArrowLink
          style={{
            fontFamily: 'Open Sans',
            fontStyle: 'normal',
            color: '#969696',
          }}
          className='mt-md:text-base'
          href='https://www.youtube.com/watch?v=eRsvduJh3Lo'
        >
          Details
        </ArrowLink>
      </div>
    </Layout>
  );
}

// src/pages/swollenballsallegations.vue
<template>
	<!-- game -->
	<Script src="scripts/chrome_game.js" />
	<div class="h-[33vh] px-4" id="game"></div>

	<br />

	<div class="flex flex-col mx-20 gap-y-10">
		<div class="flex flex-col text-left gap-y-3">
			<h1 class="text-xl text-red-600 md:text-4xl">
				⚠️ THIS PAGE HAS BEEN SEIZED
			</h1>
			<h2 class="text-base md:text-2xl">
				<span class="font-bold">Pokelawls, Inc.™</span> has ordered an
				immediate shutdown of this page, by court order.
			</h2>
		</div>
		<div class="text-right">
			<p
				class="mt-md:text-base underline decoration-dashed hover:decoration-solid text-gray-500"
			>
				<a href="https://www.youtube.com/watch?v=eRsvduJh3Lo">
					Details >
				</a>
			</p>
		</div>
	</div>
</template>

<style>
body {
	font-family: "Open Sans";
	@apply bg-white text-black;
}
</style>
